### ISSUE TITLE
Countdown to be without months

### ISSUE THREAD

**Issue by timjasch** [TadeSF/long-distance-timer#1]
Hey,

fantastic work so far! I have three minor design requests: 
First, I would prefer the countdown to be without months; just a personal preference. Also, this keeps consistency with the verbal timer below. 
Second, I would prefer a less intense blue and orange on the action buttons in the chat window. I think orange/blue is a good choice, but maybe more to the contrast level of the chat-boxes themselves.
Third, is there a good clock-template with hours marked on the dial?  The current version is a bit hard-to-read.

But it looks very good and is already, from what I can tell, fully functional!
Best

**Comment by Strehk** [comment]
Thanks a lot for your feedback, I'll handle the first request in this issue and I have diverted the others to new issues.

**Comment by Strehk** [comment]
The reason behind the months is, that the Animation Component that comes with DaisyUI (the library that allows for the fancy scrolling motion when a number changes) only allows for two digit Numbers (therefore up to 99).

I see two possibilites how to tackel this:
1. I display only days if daysLeft < 100 and otherwise display months as is now
2. Since changing days only happens not very often, we could also omit the usage of the Animation Component for the days only (or only if daysLeft < 100).

What do you prefer?

**Comment by timjasch** [comment]
Hey Tade,

2. possibility sounds good! Ommiting the animation on the day counter is totally fine; including it again if daysLeft<100 would be nice, but not a crucial in any sense.

**Comment by Strehk** [comment]
Sure, np. One followup styling question. Do you prefer the clock style we had or do you like this boxed style better? I like it, I think it gives it a nice airport-flip-display kinda vibe. Dark or Light (or ofc any color) possible, with shaddow or without? Just as a little inspiration.

I think the biggest reason i like this better, ist that we can omit the somehow indecisive looking `:` and `|`

![CleanShot 2024-05-22 at 22 49 29@2x](https://github.com/TadeSF/long-distance-timer/assets/42637916/ad32fedd-ea77-4ac8-b1e4-e98b2ccf88e8)
![CleanShot 2024-05-22 at 22 51 08@2x](https://github.com/TadeSF/long-distance-timer/assets/42637916/93bb3888-b9b0-42d4-9c54-72f01587c72f)
![CleanShot 2024-05-22 at 22 54 56@2x](https://github.com/TadeSF/long-distance-timer/assets/42637916/ffc3dde5-30ce-444d-99f6-f9ed93dfae40)

**Comment by timjasch** [comment]
You hit the mark with this one! looks perfect and gives it a "neater" look, as it emphasises what is at the heart of this project. I prefer the light design. Concerning shadow, the bottom one look great, so whatever is the configuration there.
