### ISSUE TITLE
Button Colors

### ISSUE THREAD

**Issue by Strehk** [TadeSF/long-distance-timer#2]
Tim would prefer a less intense blue and orange on the action buttons in the chat window. I think orange/blue is a good choice, but maybe more to the contrast level of the chat-boxes themselves.

**Comment by Strehk** [comment]
@timjasch Sure, no Problem ;)

These are the default DaisyUI Colors for "primary" and "warning" Components and I did not change them.

I'd suggest you pick a hex/rgb color for each of the following signals and I'll implement them.
 - `primary`
 - `secondary`
 - `accent`
 - `neutral` (usually grayish)
 - `info` (usually blue)
 - `warning` (usually yellow/orange)
 - `error` (usually red)
 
 Feel free to play around with the values on this theme generator:
[https://daisyui.com/theme-generator/](https://daisyui.com/theme-generator/)

If you want to make life easier for me, just select color values in the generator and paste the generated `tailwind.config.js` code here

**Comment by Strehk** [comment]
I would then suggest to make the tones of the speech bubbles match the primary and secondary colors (so if you want to stay with a blue/orange feel, your primary should be blue and your secondary should be orange :)

**Comment by timjasch** [comment]
Hey Tage,

played around with the website and came up with this (which is very open to discussion/changes if it looks bad according to your judgement):

  daisyui: {
      themes: [
        {
          mytheme: {
          
 "primary": "#fde68a",
          
 "secondary": "#c4b5fd",
          
 "accent": "#84cc16",
          
 "neutral": "#d1d5db",
          
 "base-100": "#ffffff",
          
 "info": "#2563eb",
          
 "success": "#16a34a",
          
 "warning": "#f59e0b",
          
 "error": "#ff0000",
          },
        },
      ],
    },

I would like to keep the (approximate) colours of the text bubbles, so feel free to adjust the primary and secondary colour if they are not the same/similar. Keeping "Warning" and "Primary" as the buttons is maybe not the best idea, as both colours are orange/yellowish in this configuration. "Warning" is good for "Abbrechen", but maybe "Senden" should be in the "Secondary" (or "Accent") colour instead.
