### ISSUE TITLE
Less minimalistic clockface for better readability

### ISSUE THREAD

**Issue by Strehk** [TadeSF/long-distance-timer#3]
@timjasch I can underlay any clockface you like. Do you have a certain style in mind? You can look [here](https://stock.adobe.com/de/search?filters%5Bcontent_type%3Aphoto%5D=0&filters%5Bcontent_type%3Aillustration%5D=0&filters%5Bcontent_type%3Azip_vector%5D=1&filters%5Bcontent_type%3Avideo%5D=0&filters%5Bcontent_type%3Atemplate%5D=0&filters%5Bcontent_type%3A3d%5D=0&filters%5Bcontent_type%3Aimage%5D=1&k=clock+face&order=relevance&safe_search=1&limit=100&search_page=1&search_type=filter-select&acp=&aco=clock+face&get_facets=1) for inspiration

**Comment by timjasch** [comment]
A style like this or similar would be great:
https://stock.adobe.com/de/images/clock-face-blank-vector-illustration/319218008?prev_url=detail
